[package]
name = "study-mlnote-in-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.63"
plotters = "0.3.3"
smartcore = "0.2.1"
